# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Ham-Device-FT950
version:      0.29.4
version_from: lib/Ham/Device/FT950.pm
installdirs:  site
requires:
    Device::SerialPort:            0.22

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
